### ISSUE TITLE
Unable to generate .itp file for linear molecules with triple bonds

### ISSUE THREAD

**Issue by pchau1807** [leelasd/ligpargen#42]
[X ] I believe this to be a bug with LigParGen 

## Issue Information
Software name & Version : LigParGen local version

## Expected Behavior
Entered the SMILES of linear molecules with a triple bond into LigParGen to receive topology and parameters. Example of SMILES: CCCC#C
 LigParGen -s 'CCCC#C' -r 'CCCC#C' -c 0 -o 0 -l
## Actual Behavior
Instead of a successful generation of topology files, I received the error message:
LBCC converter is activated
1 molecule converted
77 audit log messages 
MOLECULE HAS A CHARGE of 0
Traceback (most recent call last):
  File "/home/pchau/anaconda2/envs/my-rdkit-env/bin/LigParGen", line 10, in <module>
    sys.exit(main())
  File "/home/pchau/anaconda2/envs/my-rdkit-env/lib/python3.6/site-packages/LigParGen/Converter.py", line 90, in main
    convert(**vars(args))
  File "/home/pchau/anaconda2/envs/my-rdkit-env/lib/python3.6/site-packages/LigParGen/Converter.py", line 144, in convert
    mol = BOSSReader('%s.z' % resname, optim, charge, lbcc)
  File "/home/pchau/anaconda2/envs/my-rdkit-env/lib/python3.6/site-packages/LigParGen/BOSSReader.py", line 283, in __init__
    self.refine_data(optim, charge, lbcc)
  File "/home/pchau/anaconda2/envs/my-rdkit-env/lib/python3.6/site-packages/LigParGen/BOSSReader.py", line 507, in refine_data
    lbcc_MD = self.get_ImpDat(optim, charge)
  File "/home/pchau/anaconda2/envs/my-rdkit-env/lib/python3.6/site-packages/LigParGen/BOSSReader.py", line 496, in get_ImpDat
    sdat[impDat['ADDinit']:impDat['ADDfinal']])
KeyError: 'ADDinit'

However, I can generate the topology and parameters of this same chemical if I used the LigParGen web server instead. 

Is it something wrong with my local version?

Thank you so much for your time and consideration.

Best regards,
Phuong

**Comment by mettlyz** [comment]
I have similar problem. Work well online, but got stucked after MOLECULE HAS A CHARGE of 0 at local server.
