### ISSUE TITLE
Problem of installing LigParGen Server Locally

### ISSUE THREAD

**Issue by sbkk000** [leelasd/ligpargen#75]
- [x] I believe this to be a bug with LigParGen 
- [x] This is a feature request

## Issue Information
Software name & Version : LigParGen 
Method:

## Actual Behavior
I tried to install it strictly according to the tutorial of this blog
[How to Install LigParGen Server Locally ?](https://www.linkedin.com/pulse/how-install-ligpargen-server-locally-leela-sriram-dodda)

I have created an conda environment for LigParGen installing.

1. python=3.6.13
2. ligpargen = 2.1
3. numpy = 1.19.5
4. openbabel = 2.4.1
5. pandas = 1.1.5
6. networkx = 2.3

Finally, the error message when running the test command is as follows:
`$ LigParGen -s 'c1ccccc1' -r BNZ -c 0 -o 0 -l`

```
LBCC converter is activated
1 molecule converted
89 audit log messages 
MOLECULE HAS A CHARGE of 0
sh: 1: /home/x/boss/scripts/xZCM1A: Permission denied
cp: cannot stat 'sum': No such file or directory
sh: 1: /home/x/boss/scripts/xSPM: Permission denied
/bin/cp: cannot stat 'sum': No such file or directory
sh: 1: /home/x/boss/scripts/xSPM: Permission denied
/bin/cp: cannot stat 'sum': No such file or directory
Traceback (most recent call last):
  File "/home/x/anaconda3/envs/ligpargen/bin/LigParGen", line 8, in <module>
    sys.exit(main())
  File "/home/x/anaconda3/envs/ligpargen/lib/python3.6/site-packages/LigParGen/Converter.py", line 90, in main
    convert(**vars(args))
  File "/home/x/anaconda3/envs/ligpargen/lib/python3.6/site-packages/LigParGen/Converter.py", line 144, in convert
    mol = BOSSReader('%s.z' % resname, optim, charge, lbcc)
  File "/home/x/anaconda3/envs/ligpargen/lib/python3.6/site-packages/LigParGen/BOSSReader.py", line 283, in __init__
    self.refine_data(optim, charge, lbcc)
  File "/home/x/anaconda3/envs/ligpargen/lib/python3.6/site-packages/LigParGen/BOSSReader.py", line 507, in refine_data
    lbcc_MD = self.get_ImpDat(optim, charge)
  File "/home/x/anaconda3/envs/ligpargen/lib/python3.6/site-packages/LigParGen/BOSSReader.py", line 447, in get_ImpDat
    odat = Refine_file('/tmp/out')
  File "/home/x/anaconda3/envs/ligpargen/lib/python3.6/site-packages/LigParGen/BOSSReader.py", line 266, in Refine_file
    flines = open(fname, 'r+')
IsADirectoryError: [Errno 21] Is a directory: '/tmp/out'

```

I tried the following operation, but I still got an error: 
`$ chmod +x xZCM1A xSPM xSPM `

```
LBCC converter is activated
1 molecule converted
89 audit log messages 
MOLECULE HAS A CHARGE of 0
sh: 1: /home/x/boss/scripts/xZCM1A: not found
cp: cannot stat 'sum': No such file or directory
sh: 1: /home/x/boss/scripts/xSPM: not found
/bin/cp: cannot stat 'sum': No such file or directory
sh: 1: /home/x/boss/scripts/xSPM: not found
/bin/cp: cannot stat 'sum': No such file or directory
Traceback (most recent call last):
  File "/home/x/anaconda3/envs/ligpargen/bin/LigParGen", line 8, in <module>
    sys.exit(main())
  File "/home/x/anaconda3/envs/ligpargen/lib/python3.6/site-packages/LigParGen/Converter.py", line 90, in main
    convert(**vars(args))
  File "/home/x/anaconda3/envs/ligpargen/lib/python3.6/site-packages/LigParGen/Converter.py", line 144, in convert
    mol = BOSSReader('%s.z' % resname, optim, charge, lbcc)
  File "/home/x/anaconda3/envs/ligpargen/lib/python3.6/site-packages/LigParGen/BOSSReader.py", line 283, in __init__
    self.refine_data(optim, charge, lbcc)
  File "/home/x/anaconda3/envs/ligpargen/lib/python3.6/site-packages/LigParGen/BOSSReader.py", line 507, in refine_data
    lbcc_MD = self.get_ImpDat(optim, charge)
  File "/home/x/anaconda3/envs/ligpargen/lib/python3.6/site-packages/LigParGen/BOSSReader.py", line 447, in get_ImpDat
    odat = Refine_file('/tmp/out')
  File "/home/x/anaconda3/envs/ligpargen/lib/python3.6/site-packages/LigParGen/BOSSReader.py", line 266, in Refine_file
    flines = open(fname, 'r+')
IsADirectoryError: [Errno 21] Is a directory: '/tmp/out'
```

What should I do to solve this problem?

**Comment by RaphaelRobidas** [comment]
The scripts that are "not found" use csh. I had the same issue and fixed it by installing csh.

**Comment by eastsheng** [comment]
I had the same issue, did you fix it?

**Comment by GsGithub17** [comment]
I have the same issue. 

Is this solved? Any suggestions?
